#!/usr/bin/python3
# pgpcr-part device label
# Parition a given device and give it the specified label
# Must be run as root

import parted, sys, subprocess

if len(sys.argv) <= 1:
	print("Need a disk to partition!")
	sys.exit(1)

dev = parted.getDevice(sys.argv[1])
disk = parted.freshDisk(dev, 'msdos')
geo = parted.Geometry(device=dev, start=1, length=dev.getLength()-1)
fs = parted.FileSystem(type="ext4", geometry=geo)
part = parted.Partition(disk=disk, type=parted.PARTITION_NORMAL, fs=fs, geometry=geo)
if len(sys.argv) >= 3:
	part.name = sys.argv[2]
disk.addPartition(part, dev.optimalAlignedConstraint)
disk.commit()

subprocess.run(["/sbin/mkfs.ext4", "-F", part.path])
