#!/usr/bin/python3
# pgpcr-part device label
# Parition a given device and give it the specified label
# Must be run as root

import parted, sys, subprocess

if len(sys.argv) <= 1:
	print("Need a disk to partition!")
	sys.exit(1)
log = open("/home/pgp/pgpcr-part.log", "a")
log.write(sys.argv[1]+"\n")
dev = parted.getDevice(sys.argv[1])
disk = parted.freshDisk(dev, 'msdos')
geo = parted.Geometry(device=dev, start=1, length=dev.getLength()-1)
fs = parted.FileSystem(type="ext4", geometry=geo)
part = parted.Partition(disk=disk, type=parted.PARTITION_NORMAL, fs=fs, geometry=geo)
disk.addPartition(part, dev.optimalAlignedConstraint)
disk.commit()

mkfs = ["mkfs.ext4", "-F", part.path]
if len(sys.argv) >= 3:
	mkfs.extend(["-L", sys.argv[2]])
log.write(str(dev)+"\n"+str(disk)+"\n"+str(part)+"\n"+str(mkfs)+"\n")
log.flush()
subprocess.run(mkfs, stdout=log, stderr=log)
log.write("\n\n")
log.close()
